# UI Colors based on no-clown-fiesta theme palette
source-list-line-color: "\x1b[38;2;55;55;55m"         # gray (#373737)
source-list-keyword-color: "\x1b[38;2;126;151;171m"   # gray_blue (#7E97AB)
source-list-string-color: "\x1b[38;2;162;181;193m"    # medium_gray_blue (#A2B5C1)
source-list-number-color: "\x1b[38;2;180;105;88m"     # red (#b46958)
source-list-comment-color: "\x1b[38;2;114;114;114m"   # medium_gray (#727272)
source-list-arrow-color: "\x1b[38;2;225;225;225m"     # white (#E1E1E1)
source-list-tab-color: "\x1b[38;2;55;55;55m"          # gray (#373737)

# Source code display settings
source-list-line-count: 25
tab: "⇥ "
highlight: true

# Data display limits
max-array-values: 64
max-string-len: 4096
max-variable-recurse: 5
show-hex-dump: true
show-locals-on-backtrace: true

# Assembly settings
disassemble-flavor: intel

# Debug info
debug-info-directories: ["/usr/lib/debug/.build-id"]

# Search settings
case-insensitive-search: true

# Terminal settings
terminal-width: 120

# Command history
history-file: "~/.delve_history"
history-limit: 1000
