# Preferred ANSI color for source
source-list-line-color: "\x1b[34m"
source-list-keyword-color: "\x1b[0m"
source-list-string-color: "\x1b[92m"
source-list-number-color: "\x1b[0m"
source-list-comment-color: "\x1b[95m"
source-list-arrow-color: "\x1b[93m"
source-list-tab-color: "\x1b[90m"

# What is printed instead of '\t'.
tab: "⇥ "

# Number of lines printed above and below cursor when listing source code.
source-list-line-count: 25

# Provided aliases will be added to the default aliases for a given command.
aliases:
  ls: ["ll"]

# Maximum number of elements loaded from an array.
max-array-values: 64

# Maximum loaded string length.
max-string-len: 4096

# Output evaluation.
max-variable-recurse: 5

# Syntax flavor of assembly (intel, gnu, go).
disassemble-flavor: intel

# List of directories to use when searching for separate debug info files.
debug-info-directories: ["/usr/lib/debug/.build-id"]
