# Source code display settings
source-list-line-count: 25
tab: "⇥ "
highlight: true

# Data display limits
max-array-values: 64
max-string-len: 4096
max-variable-recurse: 5
show-hex-dump: true
show-locals-on-backtrace: true

# Assembly settings
disassemble-flavor: intel

# Search settings
case-insensitive-search: true

# Terminal settings
terminal-width: 120

# Command history
history-file: "~/.delve_history"
history-limit: 1000
