# TODO: refine one key at the time
attribute = "white"
keyword = "gray_blue"
"keyword.directive" = "red"
namespace = "gray_blue"
punctuation = "white"
"punctuation.delimiter" = "white"
operator = "white"
special = "cyan"
"variable.other.member" = "white"
variable = "white"
"variable.parameter" = { fg = "medium_gray_blue" }
"variable.builtin" = "gray_blue"
type = "white"
"type.builtin" = "gray_blue"
constructor = "white"
function = "cyan"
"function.macro" = "cyan"
"function.builtin" = "cyan"
tag = "blue"
comment = "medium_gray"
constant = "white"
"constant.builtin" = "white"
string = "medium_gray_blue"
"constant.numeric" = "red"
"constant.character.escape" = "cyan"
label = "white"
tabstop = { modifiers = ["italic"], bg = "alt_bg" }

"markup.heading" = "gray_blue"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "light_gray", modifiers = ["underlined"] }
"markup.link.text" = "blue"
"markup.raw" = "blue"

"diff.plus" = "#586935"
"diff.minus" = "#984936"
"diff.delta" = "#51657B"

"ui.background" = { bg = "bg" }
"ui.background.separator" = { fg = "gray" }
"ui.linenr" = { fg = "gray" }
"ui.linenr.selected" = { fg = "light_gray", bold = true }
"ui.statusline" = { fg = "light_gray", bg = "alt_bg" }
"ui.statusline.inactive" = { fg = "gray", bg = "alt_bg" }
"ui.popup" = { bg = "alt_bg" }
"ui.window" = { fg = "gray" }
"ui.text" = { fg = "fg" }
"ui.text.focus" = { fg = "white" }
"ui.text.inactive" = "gray"
"ui.text.directory" = { fg = "blue" }
"ui.virtual" = { fg = "gray" }
"ui.virtual.ruler" = { bg = "alt_bg" }
"ui.virtual.jump-label" = { fg = "red", modifiers = ["bold"] }
"ui.virtual.indent-guide" = { fg = "gray" }

"ui.selection" = { bg = "gray" }
"ui.selection.primary" = { bg = "gray" }
"ui.cursor.select" = { bg = "gray_blue" }
"ui.cursor.insert" = { bg = "white" }
"ui.cursor.primary.select" = { bg = "gray_blue" }
"ui.cursor.primary.insert" = { bg = "white" }
"ui.cursor.match" = { fg = "alt_bg", bg = "light_gray" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "alt_bg" }
"ui.highlight" = { bg = "alt_bg" }
"ui.highlight.frameline" = { bg = "#36383F" }
"ui.debug" = { fg = "red" }
"ui.debug.breakpoint" = { fg = "red" }
"ui.menu" = { fg = "light_gray", bg = "alt_bg" }
"ui.menu.selected" = { fg = "bg", bg = "fg" }
"ui.menu.scroll" = { fg = "gray", bg = "light_gray" }

"diagnostic.hint" = { underline = { color = "hint", style = "curl" } }
"diagnostic.info" = { underline = { color = "info", style = "curl" } }
"diagnostic.warning" = { underline = { color = "warning", style = "curl" } }
"diagnostic.error" = { underline = { color = "error", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

warning = "warning"
error = "error"
info = "info"
hint = "hint"

[palette]
fg = "#E1E1E1"
bg = "#151515"
alt_bg = "#171717"
gray = "#373737"
light_gray = "#AFAFAF"
blue = "#BAD7FF"
gray_blue = "#7E97AB"
medium_gray_blue = "#A2B5C1"
cyan = "#88afa2"
red = "#b46958"
yellow = "#F4BF75"
purple = "#AA749F"
