# TODO: find a way to attach scls and uwu to all filetypes
[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 100
feature_words = true
feature_snippets = true
snippets_first = true

[language-server.ty.config]
ty.experimental.completions.enable = true

[language-server.uwu]
command = "uwu_colors"

[language-server.ty]
command = "ty"
args = [ "server" ]

[[language]]
name = "hcl"
language-servers = [ "terraform-ls", "scls" ]

[[language]]
name = "toml"
language-servers = [ "scls", "uwu"]

[[language]]
name = "python"
language-servers = ["pyright"]
