# TODO: find a way to attach scls and uwu to all filetypes
# Completion for regular words
[language-server.scls]
command = "simple-completion-language-server"

[language-server.uwu]
command = "uwu_colors"

[language-server.scls.config]
max_completion_items = 100           # set max completion results len for each group: words, snippets, unicode-input
feature_words = true                 # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default

[[language]]
name = "python"
language-servers = [ "scls", "pylsp", "ruff" ]

[[language]]
name = "hcl"
language-servers = [ "scls" ]

[[language]]
name = "toml"
language-servers = [ "scls", "uwu"]
